[manager]
prepend_keymap = [
  { on = [ "<Esc>" ], run = "quit", desc = "Exit yazi" },
  { on = [ "f" ], run = "find --smart", desc = "Find next file" },
  { on = [ "/" ], run = "filter", desc = "Filter files" },
]
